version: '2'

services: 
    rails:
        image: "nu12/audio-converter:latest"
        ports: 
            - "80:3000"
        links:
            - "redis"
        restart: unless-stopped
    redis:
        image: redis:5.0
